#!/usr/bin/env bash

#DATABASE_URL='postgres://mvoghljaxv:LvdZqfwJLEKuKuhWbFC6@ec2-50-16-215-157.compute-1.amazonaws.com/mvoghljaxv'
#jdbc:postgresql://host:port/database?user=userName&password=pass
#perl -p -e 's/postgres\:\/\/(.+)\:(.+)/$

if [ -n "$DATABASE_URL" ]; then
 export      JDBC_URL=`echo $DATABASE_URL | perl -p -e 's/postgres\:\/\/(.+)\:(.+)\@(.+)\/(.+)/jdbc\:postgresql\:\/\/$3\/$4\?user\=$1\&password\=$2/'`
 export     JDBC_HOST=`echo $DATABASE_URL | perl -p -e 's/postgres\:\/\/(.+)\:(.+)\@(.+)\/(.+)/$3/'`
 export     JDBC_USER=`echo $DATABASE_URL | perl -p -e 's/postgres\:\/\/(.+)\:(.+)\@(.+)\/(.+)/$1/'`
 export JDBC_PASSWORD=`echo $DATABASE_URL | perl -p -e 's/postgres\:\/\/(.+)\:(.+)\@(.+)\/(.+)/$2/'`
 export   JDBC_DBNAME=`echo $DATABASE_URL | perl -p -e 's/postgres\:\/\/(.+)\:(.+)\@(.+)\/(.+)/$4/'`
fi

java "$@"
